use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir);

    // Pre-assemble pvm.s (COR24 assembly → machine code) at build time.
    // This avoids running the COR24 assembler in WASM at runtime.
    let pvm_source = std::fs::read_to_string("asm/pvm.s").expect("asm/pvm.s");
    let mut asm = cor24_emulator::Assembler::new();
    let result = asm.assemble(&pvm_source);
    if !result.errors.is_empty() {
        for e in &result.errors {
            eprintln!("pvm.s: {e}");
        }
        panic!("pvm.s assembly failed");
    }
    // Write assembled binary
    std::fs::write(out_path.join("pvm.bin"), &result.bytes).unwrap();
    // Write key label addresses as Rust source
    let labels = [
        (
            "vm_state",
            result.labels.get("vm_state").copied().unwrap_or(0),
        ),
        (
            "eval_stack",
            result.labels.get("eval_stack").copied().unwrap_or(0),
        ),
        (
            "call_stack",
            result.labels.get("call_stack").copied().unwrap_or(0),
        ),
        (
            "code_seg",
            result
                .labels
                .get("code_buf")
                .or(result.labels.get("code_seg"))
                .copied()
                .unwrap_or(0),
        ),
        (
            "vm_loop",
            result.labels.get("vm_loop").copied().unwrap_or(0),
        ),
        (
            "code_ptr",
            result.labels.get("code_ptr").copied().unwrap_or(0),
        ),
    ];
    let mut labels_rs = String::from("// Generated by build.rs — do not edit\n");
    labels_rs.push_str("pub const PVM_LABELS: &[(&str, u32)] = &[\n");
    for (name, addr) in &labels {
        labels_rs.push_str(&format!("    (\"{name}\", 0x{addr:06X}),\n"));
    }
    labels_rs.push_str("];\n");
    std::fs::write(out_path.join("pvm_labels.rs"), labels_rs).unwrap();
    println!("cargo:rerun-if-changed=asm/pvm.s");

    // Pre-assemble demo .spc files to .p24 binaries
    let demos_dir = std::path::Path::new("demos");
    for entry in std::fs::read_dir(demos_dir).expect("demos/ directory") {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "spc") {
            let source = std::fs::read_to_string(&path).unwrap();
            let p24 = pa24r::assemble_to_p24(&source).unwrap_or_else(|errs| {
                let msgs: Vec<String> = errs.iter().map(|e| e.to_string()).collect();
                panic!("{}: {}", path.display(), msgs.join("; "));
            });
            let stem = path.file_stem().unwrap().to_str().unwrap();
            std::fs::write(out_path.join(format!("{stem}.p24")), &p24).unwrap();
        }
    }
    println!("cargo:rerun-if-changed=demos");

    // Short git SHA
    let sha = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // Build host
    let host = Command::new("hostname")
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // ISO timestamp
    let timestamp = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    println!("cargo:rustc-env=BUILD_SHA={sha}");
    println!("cargo:rustc-env=BUILD_HOST={host}");
    println!("cargo:rustc-env=BUILD_TIMESTAMP={timestamp}");
}
